// Code generated by internal/gen from the vendored nvim-lspconfig corpus.
// DO NOT EDIT — run `go generate ./internal/serverdef/` instead.
//
// Corpus:   nvim-lspconfig @ bff1bd61cb1455040533201ca1edf1e84efa578f
// Upstream: https://github.com/neovim/nvim-lspconfig
// License:  Apache-2.0 — see internal/gen/corpus/nvim-lspconfig/LICENSE.md and ATTRIBUTION
// Snapshot: internal/gen/corpus/nvim-lspconfig (checked in; generation reads nothing else and
//           reaches no network)
//
// Each definition below says which of its keys came from the corpus,
// which were curated and why, and what the corpus says that this table
// deliberately does not carry. See internal/gen/curate.go for the
// policy behind those choices.

package serverdef

// generatedProvenance records where the defaults came from, so that
// `lightspeed servers` and `lightspeed doctor` can attribute them
// without hard-coding the corpus anywhere else.
var generatedProvenance = Provenance{
	Corpus:   "nvim-lspconfig",
	Upstream: "https://github.com/neovim/nvim-lspconfig",
	Commit:   "bff1bd61cb1455040533201ca1edf1e84efa578f",
	License:  "Apache-2.0",
	Snapshot: "internal/gen/corpus/nvim-lspconfig",
}

// generatedBuiltins is the built-in default layer of PLAN §6 item 3:
// the servers that answer on a clean machine with no configuration at
// all, as long as their binaries are on PATH (item 4).
var generatedBuiltins = []*ServerDef{
	// gopls — nvim-lspconfig/lsp/gopls.lua
	//   from the corpus:
	//     server.command, activation.languages
	//   curated:
	//     activation.root_markers — upstream computes the root in Lua;
	//       this is that function's own chain, `vim.fs.root(fname,
	//       'go.work') or vim.fs.root(fname, 'go.mod') or
	//       vim.fs.root(fname, '.git')`
	//     activation.globs — the corpus has no globs: Neovim
	//       dispatches on filetype, lightspeed on paths
	//     install.mise — the version PLAN §6 pins, and the one
	//       internal/gopls is vendored from; pinning here is only
	//       meaningful because mise records a checksum for it
	//   not imported:
	//     settings — editor policy (semantic tokens, code lenses,
	//       inlay hints); PLAN §2 makes those non-goals
	//     root_dir — a Lua function; declarative config cannot express
	//       it
	{
		SchemaVersion: SchemaVersion,
		Name:          "gopls",
		Activation: Activation{
			Languages: []string{
				"go",
				"gomod",
				"gowork",
				"gotmpl",
			},
			Globs: []string{
				"**/*.go",
				"**/go.mod",
				"**/go.work",
			},
			RootMarkers: []string{
				"go.work",
				"go.mod",
				".git",
			},
			Priority: DefaultPriority,
		},
		Server: Server{
			Command: []string{
				"gopls",
			},
			Transport: TransportStdio,
		},
		Install: Install{Mise: "go:golang.org/x/tools/gopls@v0.23.0"},
	},
	// clangd — nvim-lspconfig/lsp/clangd.lua
	//   from the corpus:
	//     server.command, activation.languages, activation.root_markers
	//   curated:
	//     activation.globs — the corpus has no globs: Neovim
	//       dispatches on filetype, lightspeed on paths
	//     install.mise — clangd has no mise registry entry, so the
	//       backend is named explicitly. It is the one install spec in
	//       this table that could not be checked against a registry
	//       offline; `lightspeed doctor` reports mise's own failure
	//       verbatim if it is wrong
	//   not imported:
	//     filetypes — dropped the Neovim-only filetype(s) c.doxygen,
	//       cpp.doxygen
	//     capabilities — a table
	//     get_language_id — a Lua function; declarative config cannot
	//       express it
	//     on_attach — a Lua function; declarative config cannot
	//       express it
	//     on_init — a Lua function; declarative config cannot express
	//       it
	{
		SchemaVersion: SchemaVersion,
		Name:          "clangd",
		Activation: Activation{
			Languages: []string{
				"c",
				"cpp",
				"objective-c",
				"objective-cpp",
				"cuda-cpp",
			},
			Globs: []string{
				"**/*.c",
				"**/*.h",
				"**/*.cc",
				"**/*.cpp",
				"**/*.cxx",
				"**/*.c++",
				"**/*.hh",
				"**/*.hpp",
				"**/*.hxx",
				"**/*.h++",
				"**/*.m",
				"**/*.mm",
				"**/*.cu",
				"**/*.cuh",
			},
			RootMarkers: []string{
				".clangd",
				".clang-tidy",
				".clang-format",
				"compile_commands.json",
				"compile_flags.txt",
				"configure.ac",
				".git",
			},
			Priority: DefaultPriority,
		},
		Server: Server{
			Command: []string{
				"clangd",
			},
			Transport: TransportStdio,
		},
		Install: Install{Mise: "ubi:clangd/clangd"},
	},
	// lua-ls — nvim-lspconfig/lsp/lua_ls.lua
	//   from the corpus:
	//     server.command, activation.languages
	//   curated:
	//     activation.root_markers — upstream's list is a version test
	//       over two marker groups; this is those groups concatenated in
	//       order, which is what upstream's own pre-0.11.3 branch does
	//     activation.globs — the corpus has no globs: Neovim
	//       dispatches on filetype, lightspeed on paths
	//     install.mise — the corpus knows nothing about installation
	//   not imported:
	//     settings — editor policy (semantic tokens, code lenses,
	//       inlay hints); PLAN §2 makes those non-goals
	//     root_markers — a computed expression
	{
		SchemaVersion: SchemaVersion,
		Name:          "lua-ls",
		Activation: Activation{
			Languages: []string{
				"lua",
			},
			Globs: []string{
				"**/*.lua",
			},
			RootMarkers: []string{
				".emmyrc.json",
				".luarc.json",
				".luarc.jsonc",
				".luacheckrc",
				".stylua.toml",
				"stylua.toml",
				"selene.toml",
				"selene.yml",
				".git",
			},
			Priority: DefaultPriority,
		},
		Server: Server{
			Command: []string{
				"lua-language-server",
			},
			Transport: TransportStdio,
		},
		Install: Install{Mise: "lua-language-server"},
	},
	// pyright — nvim-lspconfig/lsp/pyright.lua
	//   from the corpus:
	//     server.command, activation.languages, activation.root_markers
	//   curated:
	//     activation.globs — the corpus has no globs: Neovim
	//       dispatches on filetype, lightspeed on paths
	//     install.mise — the corpus knows nothing about installation
	//   not imported:
	//     settings — editor policy (semantic tokens, code lenses,
	//       inlay hints); PLAN §2 makes those non-goals
	//     on_attach — a Lua function; declarative config cannot
	//       express it
	{
		SchemaVersion: SchemaVersion,
		Name:          "pyright",
		Activation: Activation{
			Languages: []string{
				"python",
			},
			Globs: []string{
				"**/*.py",
				"**/*.pyi",
			},
			RootMarkers: []string{
				"pyrightconfig.json",
				"pyproject.toml",
				"setup.py",
				"setup.cfg",
				"requirements.txt",
				"Pipfile",
				".git",
			},
			Priority: DefaultPriority,
		},
		Server: Server{
			Command: []string{
				"pyright-langserver",
				"--stdio",
			},
			Transport: TransportStdio,
		},
		Install: Install{Mise: "npm:pyright"},
	},
	// rust-analyzer — nvim-lspconfig/lsp/rust_analyzer.lua
	//   from the corpus:
	//     server.command, activation.languages
	//   curated:
	//     activation.root_markers — upstream computes the root in Lua,
	//       via `cargo metadata`, which this package will not run at build
	//       time and the router will not run at query time;
	//       rust-project.json comes first because it is an explicit,
	//       deliberate project description, and a Cargo workspace member
	//       therefore resolves to the member, not the workspace root — a
	//       documented narrowing of upstream's behaviour
	//     activation.globs — the corpus has no globs: Neovim
	//       dispatches on filetype, lightspeed on paths
	//     install.mise — the corpus knows nothing about installation
	//   not imported:
	//     settings — editor policy (semantic tokens, code lenses,
	//       inlay hints); PLAN §2 makes those non-goals
	//     before_init — a Lua function; declarative config cannot
	//       express it
	//     capabilities — a table
	//     on_attach — a Lua function; declarative config cannot
	//       express it
	//     root_dir — a Lua function; declarative config cannot express
	//       it
	{
		SchemaVersion: SchemaVersion,
		Name:          "rust-analyzer",
		Activation: Activation{
			Languages: []string{
				"rust",
			},
			Globs: []string{
				"**/*.rs",
				"**/Cargo.toml",
			},
			RootMarkers: []string{
				"rust-project.json",
				"Cargo.toml",
				".git",
			},
			Priority: DefaultPriority,
		},
		Server: Server{
			Command: []string{
				"rust-analyzer",
			},
			Transport: TransportStdio,
		},
		Install: Install{Mise: "rust-analyzer"},
	},
	// vtsls — nvim-lspconfig/lsp/vtsls.lua
	//   from the corpus:
	//     server.command, activation.languages
	//   curated:
	//     activation.root_markers — upstream computes the root in Lua:
	//       a package-manager lock file, else the working directory, and
	//       it refuses to attach at all inside a Deno project. The lock
	//       files are transcribed; tsconfig.json, jsconfig.json and
	//       package.json are added as a fallback for a checkout with no
	//       lock file, and the Deno exclusion is not expressible
	//       declaratively — a Deno project needs a .lightspeed.toml
	//     activation.globs — the corpus has no globs: Neovim
	//       dispatches on filetype, lightspeed on paths
	//     install.mise — the corpus knows nothing about installation
	//     server.initialization_options — curated; see below
	//     note — upstream sets hostInfo = 'neovim'; ours says what is
	//       actually driving the server
	//   not imported:
	//     root_dir — a Lua function; declarative config cannot express
	//       it
	{
		SchemaVersion: SchemaVersion,
		Name:          "vtsls",
		Activation: Activation{
			Languages: []string{
				"javascript",
				"javascriptreact",
				"typescript",
				"typescriptreact",
			},
			Globs: []string{
				"**/*.ts",
				"**/*.tsx",
				"**/*.mts",
				"**/*.cts",
				"**/*.js",
				"**/*.jsx",
				"**/*.mjs",
				"**/*.cjs",
			},
			RootMarkers: []string{
				"package-lock.json",
				"yarn.lock",
				"pnpm-lock.yaml",
				"bun.lockb",
				"bun.lock",
				"tsconfig.json",
				"jsconfig.json",
				"package.json",
				".git",
			},
			Priority: DefaultPriority,
		},
		Server: Server{
			Command: []string{
				"vtsls",
				"--stdio",
			},
			Transport: TransportStdio,
			InitializationOptions: map[string]any{
				"hostInfo": "lightspeed",
			},
		},
		Install: Install{Mise: "npm:@vtsls/language-server"},
	},
}
