package cli

import (
	"fmt"
	"slices"
	"strings"
)

// The agent guide: the policy text a coding agent needs to use lightspeed —
// which tool for which question, how to name a symbol, when a change is
// written, what an exit code means — generated from the command table, so
// that it cannot describe a command or a flag the binary does not have
// (docs/DECISIONS.md D43).
//
// It has two surfaces. On the command line it names commands and `--flags`; as
// an MCP tool and as the server's instructions (guideMCP) it names the tools
// and their parameters, which are not the same words: `index` is the tools
// index_status, index_build and index_clear, `--allow-dirty` is allow_dirty,
// and `install` is no tool at all.
//
// Two things are written by hand: the rules (prose that is true of the whole
// tool) and guideGroups (which commands answer which kind of question). Every
// command line in the output — its name, its arguments, its summary, its
// flags — is read from the table at the moment the guide is built. A test
// fails for a command with MCP tools that is in no group, for a group that
// names a command that does not exist, and for a `--flag` in any rendering that
// no command has.

// guideVersion is the version of the guide's shape and rules. Bump it when the
// rules change, so that a CLAUDE.md section generated by an older binary can be
// told from a current one by its marker.
const guideVersion = 1

// guideMarker and guideEnd delimit the CLAUDE.md section, so that
// `lightspeed guide --format claude-md` can be re-run and the old section
// replaced between them.
const (
	guideMarkerPrefix = "<!-- lightspeed guide"
	guideEnd          = "<!-- /lightspeed guide -->"
)

// A guideGroup is one kind of question and the commands that answer it.
type guideGroup struct {
	Title string
	// When is the one sentence that says when to reach for the group.
	When     string
	Commands []string
}

// guideGroups is the task-oriented index of the command table. A command may be
// in more than one group; a command with MCP tools must be in at least one.
var guideGroups = []guideGroup{
	{"Orient in a repository", "You do not know the codebase yet, or have a task in words and need to know where it lives.",
		[]string{"task_context", "repo_outline", "repo_map", "tree"}},
	{"Find code by name", "You know (part of) a name; this replaces grepping for a definition.",
		[]string{"search_symbols", "workspace_symbol"}},
	{"Read code", "You need a file's structure or one symbol's body; never open a whole file to find a function.",
		[]string{"outline", "symbols", "source", "context", "hover"}},
	{"Text, strings and config", "The thing is not a symbol: a string literal, a comment, a config value, a file with no language server.",
		[]string{"search_text", "file"}},
	{"Who uses this, and what does it use", "Before you trust that something is used or unused, or to follow a call or a type.",
		[]string{"definition", "references", "check_references", "implementation", "call_hierarchy", "type_hierarchy", "related"}},
	{"Imports and dependencies", "You need the file-level graph: who imports a file, what it imports, cycles.",
		[]string{"find_importers", "imports", "dependency_graph", "dependency_cycles"}},
	{"Change code safely", "Before renaming or deleting, ask the *_check commands; then rename, codeaction and format preview by default.",
		[]string{"blast_radius", "rename_check", "delete_check", "rename", "codeaction", "format"}},
	{"What changed", "You need the symbols a diff touched, or where a repository churns.",
		[]string{"changed_symbols", "churn", "hotspots"}},
	{"Health", "You are looking for compile problems or code nothing uses.",
		[]string{"check", "dead_code", "dependency_cycles"}},
	{"Setup and meta", "A language is not answering, or you want to know what this server is.",
		[]string{"servers", "doctor", "install", "index", "daemon", "guide", "version"}},
}

// guideHiddenFlags are flags a command line does not repeat: the ones every
// command has, and the workspace anchors the addressing section explains once.
var guideHiddenFlags = []string{"context", "limit", "timeout", "server", "absolute", "root", "path", "symbol", "id", "workspace"}

// guideFlagLimit bounds how many flags one command line lists.
const guideFlagLimit = 6

// guideFlagClaims are flags the prose of the guide relies on, and the commands
// that must have each of them. A test checks them against the real flags.
var guideFlagClaims = []struct {
	Flag     string
	Commands []string
}{
	{"apply", []string{"rename", "codeaction", "format"}},
	{"allow-dirty", []string{"rename", "codeaction", "format"}},
	{"id", []string{"definition", "references", "source", "context", "rename"}},
	{"symbol", []string{"definition", "references", "context", "rename"}},
	{"limit", []string{"search_symbols", "references", "search_text", "find_importers"}},
	{"budget", []string{"repo_map", "task_context"}},
	{"compact", []string{"guide"}},
}

// guideStyle selects the headings and the frame around the same text.
type guideStyle int

const (
	// guideText is plain markdown for a human or an agent that asked.
	guideText guideStyle = iota
	// guideClaudeMD is a section to paste into CLAUDE.md, framed by markers.
	guideClaudeMD
	// guideMCP is the guide as an MCP client reads it: tool names and their
	// parameters instead of commands and flags, and nothing it cannot call.
	guideMCP
)

// guideWords are the spellings that differ between the two surfaces.
type guideWords struct {
	id, sourceArg, symbol, absolute, apply, allowDirty, limit, budget string
}

func (s guideStyle) words() guideWords {
	if s == guideMCP {
		return guideWords{"`id`", "`ids` for `source`", "`symbol: \"pkg.Type.Method\"`", "`absolute: true`", "`apply: true`", "`allow_dirty: true`", "`limit`", "`budget`"}
	}
	return guideWords{"`--id`", "as the argument of `source`", "`--symbol pkg.Type.Method`", "`--absolute`", "`--apply`", "`--allow-dirty`", "`--limit`", "`--budget`"}
}

// guideToolLines are a command's tools as the MCP guide lists them: the tool's
// name, its own description (a command's summary is written for the command
// line and names flags) and its parameters.
func guideToolLines(c *command) []string {
	var lines []string
	for _, t := range c.MCP {
		var params []string
		for _, p := range t.Params {
			if !p.exposed() || slices.Contains(guideHiddenFlags, p.Flag) || slices.Contains(params, p.name()) {
				continue
			}
			params = append(params, p.name())
		}
		if len(params) > guideFlagLimit {
			params = append(params[:guideFlagLimit], "…")
		}
		line := "- `" + t.Name + "` — " + strings.TrimSuffix(t.Description, ".")
		if len(params) > 0 {
			line += " [" + strings.Join(params, " ") + "]"
		}
		lines = append(lines, line)
	}
	return lines
}

// guideToolNames are the names of a command's tools.
func guideToolNames(c *command) []string {
	var names []string
	for _, t := range c.MCP {
		names = append(names, t.Name)
	}
	return names
}

// guideCommandLine is one command as the guide lists it, read from the table.
func guideCommandLine(c *command) string {
	args := c.Args
	// Flags in the argument summary (`index ... [--root DIR]`) are the
	// command's own business; the flag list below is what the table declares.
	if i := strings.Index(args, "[--"); i >= 0 {
		args = strings.TrimSpace(args[:i])
	}
	var b strings.Builder
	b.WriteString("- `" + strings.TrimSpace(c.Name+" "+args) + "` — " + c.Summary)
	if flags := guideFlags(c); len(flags) > 0 {
		b.WriteString(" [" + strings.Join(flags, " ") + "]")
	}
	return b.String()
}

// guideFlags are the flags the command's tools declare, in declaration order,
// minus the ones every line would repeat, bounded.
func guideFlags(c *command) []string {
	var out []string
	for _, t := range c.MCP {
		for _, p := range t.Params {
			if p.Flag == "" || !p.exposed() || slices.Contains(guideHiddenFlags, p.Flag) {
				continue
			}
			if f := "--" + p.Flag; !slices.Contains(out, f) {
				out = append(out, f)
			}
		}
	}
	if len(out) > guideFlagLimit {
		out = append(out[:guideFlagLimit], "…")
	}
	return out
}

// guideData is the payload of `lightspeed guide --format json`.
type guideData struct {
	Version int    `json:"version"`
	Build   string `json:"build"`
	Compact bool   `json:"compact,omitempty"`
	// Text is the guide as markdown.
	Text   string           `json:"text"`
	Groups []guideGroupData `json:"groups"`
}

type guideGroupData struct {
	Title    string   `json:"title"`
	When     string   `json:"when"`
	Commands []string `json:"commands"`
}

// buildGuide renders the guide from the command table. compact is the short
// form the MCP server sends as its instructions.
func buildGuide(compact bool, style guideStyle) string {
	if compact {
		return compactGuide()
	}
	w := style.words()
	// The section of a CLAUDE.md is one level below the file's own title.
	top := "#"
	if style == guideClaudeMD {
		top = "##"
	}
	h := func(n int) string { return strings.Repeat("#", n-1) + top }
	var b strings.Builder
	if style == guideClaudeMD {
		fmt.Fprintf(&b, "%s v%d build %s -->\n\n", guideMarkerPrefix, guideVersion, guideBuildID())
		fmt.Fprintf(&b, "%s Code navigation: lightspeed\n\n", top)
	} else {
		fmt.Fprintf(&b, "%s Lightspeed agent guide (v%d)\n\n", top, guideVersion)
	}
	b.WriteString(`Lightspeed answers code questions through the language servers (LSP), not from a copy that can go stale: every query revalidates the files it reports on against the disk. There is no index to refresh and nothing to register after an edit.

**Never fall back to Read, Grep, Glob or Bash (cat, grep, rg, find) for code navigation. Use the tools below; Read a file only when you are about to Edit it.**

`)

	fmt.Fprintf(&b, "%s Naming a symbol or a place\n\n", h(2))
	b.WriteString("- **Ids first.** `outline`, `symbols`, `search_symbols` and `workspace_symbol` return ids like `path::Container.Name#kind`; pass one as " + w.id + " (or " + w.sourceArg + ") to `source`, `context`, `references`, `definition`, `rename` and the other symbol commands. A stale id is a `stale_id` error naming the nearest candidates: outline the file again.\n")
	b.WriteString("- A location is `file:line:col` (1-based line, byte column), `file:line` or `file:#offset`.\n")
	b.WriteString("- Or " + w.symbol + ", resolved by the server; an ambiguous name is refused with every candidate, never guessed.\n")
	b.WriteString("- Paths are workspace-relative in and out (" + w.absolute + " for absolute ones).\n\n")

	fmt.Fprintf(&b, "%s Choosing a tool\n\n", h(2))
	for _, g := range guideGroups {
		fmt.Fprintf(&b, "%s %s\n\n%s\n\n", h(3), g.Title, g.When)
		for _, name := range g.Commands {
			c := lookupCommand(name)
			switch {
			case c == nil:
			case style == guideMCP:
				for _, line := range guideToolLines(c) {
					b.WriteString(line + "\n")
				}
			default:
				b.WriteString(guideCommandLine(c) + "\n")
			}
		}
		b.WriteString("\n")
	}

	fmt.Fprintf(&b, "%s Changing code\n\n", h(2))
	b.WriteString("- `rename`, `codeaction` and `format` **preview by default** (a diff; nothing is written). Pass " + w.apply + " to write. All files are written or none.\n")
	b.WriteString("- " + w.apply + " is refused on a git worktree with uncommitted changes unless " + w.allowDirty + "; the refusal lists the dirty paths.\n")
	b.WriteString("- Before a rename or a delete, run `rename_check` or `delete_check`: they are read-only verdicts with their evidence.\n\n")

	fmt.Fprintf(&b, "%s Results and exit codes\n\n", h(2))
	b.WriteString("- Every result is a JSON envelope `{ok, data, warnings}`, or `{ok:false, error:{code, message}}`. Read `warnings`: they say when an answer is weaker than usual.\n")
	b.WriteString("- Lists are bounded. `truncated:true` (with the total) says a list was cut; raise " + w.limit + " (or " + w.budget + " for `repo_map` and `task_context`) or narrow the query.\n")
	if style == guideMCP {
		b.WriteString("- The exit code of the same command line is in the result's `_meta` (`lightspeed/exit`): ")
	} else {
		b.WriteString("- Exit codes: ")
	}
	b.WriteString("0 ok · 1 problems found, including an authoritative empty answer (nothing uses it) · 2 usage · 3 no server for the language, or `not_covered` · 4 crash or timeout · **5 not ready: the server is still indexing, so an empty answer would prove nothing; wait and retry, never read it as \"no results\".**\n")
	b.WriteString("- A language with no installed server only has `search_text`, `tree`, `file` and, where an extractor exists, `imports`. ")
	if style == guideMCP {
		b.WriteString("`doctor` says what is missing; installing is not a tool: it is `lightspeed install <name>` in a shell, which is the user's call.\n")
	} else {
		b.WriteString("`doctor` says what is missing and `install <name>` how to get it.\n")
	}
	if style == guideClaudeMD {
		b.WriteString("\n" + guideEnd + "\n")
	}
	return b.String()
}

// compactGuide is the guide as the MCP server's instructions: it is in every
// session's context, so it is rules and group members, not command lines.
func compactGuide() string {
	var b strings.Builder
	b.WriteString("Lightspeed answers code questions and applies refactors through language servers. Never stale: every query revalidates against the disk; there is no index to refresh.\n")
	b.WriteString("Never fall back to Read/Grep/Glob/Bash for code navigation; Read a file only when you are about to Edit it.\n\n")
	b.WriteString("Read symbols, not files: outline lists a file's symbols with ids (path::Container.Name#kind); source and context return one symbol by id. Name a place with location (file:line:col, 1-based line, byte column), symbol (dotted, pkg.Type.Method) or id; every symbol tool takes id. A stale id is a stale_id error naming candidates: outline the file again. Paths are workspace-relative.\n\n")
	b.WriteString("Tools by question:\n")
	for _, g := range guideGroups {
		var names []string
		for _, n := range g.Commands {
			if c := lookupCommand(n); c != nil {
				names = append(names, guideToolNames(c)...)
			}
		}
		if len(names) > 0 {
			fmt.Fprintf(&b, "- %s: %s\n", g.Title, strings.Join(names, ", "))
		}
	}
	b.WriteString("\nrename, codeaction and format preview by default and write nothing; pass apply:true to write (all files or none). apply is refused on a worktree with uncommitted changes unless allow_dirty is true. Run rename_check or delete_check first.\n\n")
	b.WriteString("Every result is an envelope {ok, data, warnings} or {ok:false, error:{code, message}}; ok:false is a tool error. Read warnings. truncated:true means a list was cut: raise limit or narrow it.\n")
	b.WriteString("not_ready means the language server is still indexing, so an empty answer would not be authoritative: wait and retry, never read it as \"no results\". An empty ok:true result is an authoritative \"none\". no_server / not_covered: that language has no server here; use search_text, tree, file (guide has details).")
	return b.String()
}

// guideBuildID is the running executable's build identity, for the marker.
func guideBuildID() string { return currentBuildInfo().Build }

// guidePayload is the JSON form.
func guidePayload(compact bool, style guideStyle) guideData {
	d := guideData{Version: guideVersion, Build: guideBuildID(), Compact: compact, Text: buildGuide(compact, style)}
	for _, g := range guideGroups {
		gd := guideGroupData{Title: g.Title, When: g.When}
		for _, n := range g.Commands {
			switch c := lookupCommand(n); {
			case c == nil:
			case style == guideMCP:
				gd.Commands = append(gd.Commands, guideToolNames(c)...)
			default:
				gd.Commands = append(gd.Commands, n)
			}
		}
		d.Groups = append(d.Groups, gd)
	}
	return d
}
